### ISSUE TITLE
Insert png onto Input and Output layers

### ISSUE THREAD

**Issue by Nqabz** [jettan/tikz_cnn#1]
Great micro. Very useful.
Do you have a convenient command for use with includegraphics for showing pictures instead of the current coloring on both input and output layers?

**Comment by qilicun** [comment]
@jettan Hi，thanks for your great work! I also think this is needed.
@Nqabz Do you have any suggestion?

**Comment by jettan** [comment]
I added an example on how to do this the easiest way possible.
