### ISSUE TITLE
Y offset 

### ISSUE THREAD

**Issue by aloukkal** [jettan/tikz_cnn#2]
Hello, 

First of all thank you. Could you please tell me how to have a Y offset ? I have tried adding a sixth argument but it soen't work. I am trying to draw a multi task network, so with multiple decoders

Regards.

**Comment by jettan** [comment]
I added support for it in the last commit. Realized I had it somewhere because one of our projects also needed it.

**Comment by aloukkal** [comment]
Thank you very much @jettan. If you have an already written code for Z coordinate offset as well it would be much appreciated.

**Comment by jettan** [comment]
Sadly, no z offset yet, but if you happen to implement it I will gladly merge the pull request!

**Comment by aloukkal** [comment]
Thanks again, If I implement it I will let you know
